harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: ingress-controller
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: Simple Rollout
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: prod
  - entityType: SERVICE
    name: Service
    value: nginx-ingress-controller
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: ${Infra}
