harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Dev Deployment
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: DEV
  workflowName: Simple Rollout
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: dev
  - entityType: SERVICE
    name: Service
    value: ${Service}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: ${Infra-Dev}
- type: ENV_STATE
  name: Rollout with Tests
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 2
  workflowName: Rollout with Tests
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: qa
  - entityType: SERVICE
    name: Service
    value: ${Service}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: test
- type: APPROVAL
  name: Approval 2
  parallel: false
  properties:
    userGroups:
    - Slack-Notification-Demo
    stageName: STAGE APPROVAL
    timeoutMillis: 86400000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE APPROVAL
- type: ENV_STATE
  name: Rollout with Tests-1
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 3
  workflowName: Rollout with Tests
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: qa
  - entityType: SERVICE
    name: Service
    value: ${Service}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: stage
