harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Dev Deployment
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: DEV
  workflowName: Simple Rollout
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: dev
  - entityType: SERVICE
    name: Service
    value: ${Service}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: ${Infra-Dev}
- type: ENV_STATE
  name: Rollout with Tests
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: QA - TEST
  workflowName: Rollout with Tests
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: qa
  - entityType: SERVICE
    name: Service
    value: ${Service}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: test
- type: APPROVAL
  name: Approval 2
  parallel: false
  properties:
    userGroups:
    - Slack-Notification-Demo
    workflowVariables: null
    stageName: STAGE APPROVAL
    timeoutMillis: 86400000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE APPROVAL
- type: ENV_STATE
  name: QA Stage Deployment
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: QA - STAGE
  workflowName: Rollout with Tests
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: qa
  - entityType: SERVICE
    name: Service
    value: ${Service}
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: stage
- type: APPROVAL
  name: Approval 4
  parallel: false
  properties:
    userGroups:
    - Slack-Notification-Demo
    workflowVariables: null
    stageName: PROD - RING 0 - APPROVAL
    timeoutMillis: 86400000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: PROD - RING 0 - APPROVAL
- type: ENV_STATE
  name: Canary Workflow - Verification
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 6
  workflowName: Canary Workflow - Verification
  workflowVariables:
  - name: verify_canary
    value: 'no'
  - entityType: ENVIRONMENT
    name: Environment
    value: prod
  - entityType: INFRASTRUCTURE_DEFINITION
    name: INFRA
    value: RING-0
  - name: metric_verification
    value: Prometheus
