harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Simple Rollout
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: PROMETHEUS
  workflowName: Simple Rollout
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: prod
  - entityType: SERVICE
    name: Service
    value: prometheus
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: tools
- type: ENV_STATE
  name: Simple Rollout-1
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: ELK
  workflowName: Simple Rollout
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: prod
  - entityType: SERVICE
    name: Service
    value: elastic-search
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: tools
